### PR TITLE
Filter 

### PR DESCRIPTION
**Pull request by zzzzshawn**
https://github.com/user-attachments/assets/123ba4bf-edbe-4b48-b61b-a20bba05546a

### CODE REVIEW

**Review by dinxsh — APPROVED** [review]
good work

**Comment by dinxsh** [comment]
could you fix merge conflicts locally than push @zzzzshawn

**Comment by zzzzshawn** [comment]
> good work

Yeah will do

**Comment by zzzzshawn** [comment]
@dinxsh im unable to fix the conflict at games/route

**Review by dinxsh — APPROVED** [review]
looks good to me now, great work!

**Pull request merged**
