### PR TITLE
Removed darkMode Issue - #184

### PR DESCRIPTION
**Pull request by JkrishnaD**
This Request is for the issue #184 Based on that issue removed all the code which is related to the dark mode.

- Along with that added few responsive to the navbar.
- Adjusted the margin tops for the sections.
- added hover effect to the feature section.

## Summary by CodeRabbit

- **Style Changes**
	- Removed dark mode styling from multiple components.
	- Simplified styling for various UI elements.
	- Adjusted margins, colors, and hover effects across the application.

- **Component Removals**
	- Deleted `ModeToggle` component.
	- Removed `ThemeProvider` component.
	- Eliminated theme switching functionality.

- **Layout Modifications**
	- Simplified navigation and footer components.
	- Removed theme-related configuration in Tailwind CSS.

These changes reflect a concerted effort to streamline the application's styling and remove dark mode support.

### CODE REVIEW

**Review by dinxsh — APPROVED** [review]
good job

**Comment by dinxsh** [comment]
could you resolve conflicts and check if dark mode is consistent throughout the website? we require you to remove the toggle on the navbar @JkrishnaD

**Comment by JkrishnaD** [comment]
@dinxsh yeah i have seen all the conflicts and toggle button is removed from navbar and there is no style which is related to darkmode in this branch.

**Comment by dinxsh** [comment]
sweet just fix the conflicts now either locally or through below provided "resolve conflicts" button @JkrishnaD and we should be good to merge this pr

**Comment by JkrishnaD** [comment]
Hey @dinxsh I resloved the conflict issues by "reslove conflicts" and it was good

**Pull request merged**
